input_data_path: "data/raw/dataset.csv"
downloading_params:
  storage: "https://drive.google.com/uc?export=download&id=1kDva3a99Y_k-TFvVL5YhvtvjhmkFFPgW"
  output_folder: "data/raw"
  filename: "dataset.csv"
train_params:
  model_type: "RandomForestRegressor"
splitting_params:
  val_size: 0.2
  random_state: 3

